app:
  restart: always
  build: ./app/
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./app:/usr/src/app
  env_file: .env
  environment:
    DEBUG: 'true'
  command: /usr/local/bin/gunicorn LiveGrip.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "3000:80"
  volumes:
    - /www/static
  volumes_from:
    - app
  links:
    - app:app

postgres:
  restart: always
  build: ./postgres/
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

mosquitto:
  restart: always
  build: ./mosquitto/
  command: mosquitto -p 8001
  ports:
    - "8001:8001"
  links:
    - app:app
  volumes_from:
    - app

redis:
  restart: always
  build: ./redis/
  ports:
    - "6379:6379"
  volumes:
    - redisdata:/data