app:
  restart: always
  build: ./app/
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./app:/usr/src/app
  env_file: .env
  command: /usr/local/bin/gunicorn LiveGrip.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "3000:80"
  volumes:
    - /www/static
  volumes_from:
    - app
  links:
    - app:app

postgres:
  restart: always
  build: ./postgres/
  expose:
    - "5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

mosquitto:
  restart: always
  build: ./mosquitto/
  command: mosquitto -p 8080
  ports:
    - "8080:8080"

redis:
  restart: always
  build: ./redis/
  expose:
    - "6379"
  volumes:
    - redisdata:/data