app:
  restart: always
  build: ./app/
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./app:/usr/src/app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "3000:80"
  volumes:
    - /www/static
  volumes_from:
    - app
  links:
    - app:app

postgres:
  restart: always
  build: ./postgres/
  expose:
    - "5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

mosquitto:
  restart: always
  build: ./mosquitto/
  ports:
    - "8080:8080"

redis:
  restart: always
  build: ./redis/
  expose:
    - "6379"
  volumes:
    - redisdata:/data

celery:
  restart: always
  build: ./celery/
  links:
    - postgres:postgres
    - redis:redis
  volumes_from:
    - app