app:
  restart: always
  build: ./app/
  expose:
    - "8000"
  links:
    - postgres:postgres
    - rethinkdb:rethinkdb
  volumes:
    - ./app:/usr/src/app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "3000:80"
  volumes:
    - /www/static
  volumes_from:
    - app
  links:
    - app:app

postgres:
  restart: always
  build: ./postgres/
  expose:
    - "5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

mosquitto:
  restart: always
  build: ./mosquitto/
  ports:
    - "8081:8081"

rethinkdb:
  restart: always
  build: ./rethinkdb/
  ports:
    - "28015:28015"
    - "29015:29015"
    - "8080:8080"

jenkins:
  restart: always
  build: ./jenkins/
  ports:
    - "8085:8085"
    - "50000:50000"
  volumes:
    - ./jenkins:/var/jenkins_home

