# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, verbose_name='Token')),
                ('expiry_date', models.DateTimeField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Tokens',
                'db_table': 'access_tokens',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='message')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('h', 'Holding'), ('p', 'Published')], default='h', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='app_version',
            field=models.CharField(default='undefined', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='unset', max_length=300, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AddField(
            model_name='message',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event', verbose_name='event'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='message user'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
