# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160725_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
