# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 21:25
from __future__ import unicode_literals

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160725_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expiry_date',
            field=models.DateTimeField(default=api.utils.new_token_expiry_date),
        ),
    ]
