# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160725_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='http://i.imgur.com/bVlVbb2.jpg', max_length=300, null=True),
        ),
    ]
