# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_app_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(default=None),
        ),
    ]
