# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160412_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='unset', max_length=200),
        ),
    ]
