# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160725_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='app_version',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=5),
        ),
    ]
