# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 01:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160725_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 26, 1, 44, 19, 74799, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Generated'),
        ),
    ]
