# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160412_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='unset', max_length=300, null=True),
        ),
    ]
