# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160727_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstoken',
            options={'ordering': ['id'], 'verbose_name': 'Access Token', 'verbose_name_plural': 'Access Tokens'},
        ),
        migrations.AlterModelOptions(
            name='firebasemessagingtoken',
            options={'ordering': ['id'], 'verbose_name': 'Firebase Token', 'verbose_name_plural': 'Firebase Tokens'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
    ]
