# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160416_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('h', 'Holding'), ('p', 'Published')], max_length=1),
        ),
    ]
