# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160416_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
    ]
