# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_message_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=70)),
                ('event_id', models.IntegerField()),
                ('body', models.TextField(default='')),
                ('profile_image', models.CharField(default='unset', max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='gcm_id',
        ),
    ]
