# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160702_0404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedisMessage',
        ),
        migrations.AddField(
            model_name='user',
            name='gcm_id',
            field=models.CharField(default='not_set', max_length=500, null=True),
        ),
    ]
