# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_user_gcm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
