# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_accesstoken'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accesstoken',
            table='access_tokens',
        ),
    ]
