# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gcm_id',
            field=models.CharField(default='not_set', max_length=500),
            preserve_default=False,
        ),
    ]
