# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160412_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('h', 'Holding'), ('p', 'Published'), ('r', 'Removed')], default='h', max_length=1),
            preserve_default=False,
        ),
    ]
